### ISSUE TITLE
Issue on Eclipse

### ISSUE THREAD

**Issue by ramsestom** [simonpoole/OpeningHoursParser#14]
Hi Simon
    I am trying to use this parser inside a java codenameone app (https://www.codenameone.com/index.html) but when I run this app from eclipse the parser fail with the following error message:

```
java.lang.IllegalArgumentException: [c@68bd1b55 is not a valid WeekDay
	at org.tomlab.myapp.common.openinghours.WeekDayRange.setEndDay(WeekDayRange.java:205)
	at org.tomlab.myapp.common.openinghours.OpeningHoursParser.weekday_range(OpeningHoursParser.java:484)
	at org.tomlab.myapp.common.openinghours.OpeningHoursParser.weekday_selector(OpeningHoursParser.java:590)
	at org.tomlab.myapp.common.openinghours.OpeningHoursParser.rule(OpeningHoursParser.java:1214)
	at org.tomlab.myapp.common.openinghours.OpeningHoursParser.rules(OpeningHoursParser.java:1265)
	at org.tomlab.myapp.common.openinghours.OpeningHours.parseOpeningHours(OpeningHours.java:43)
	at org.tomlab.myapp.MyApplication.start(MyApplication.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.codename1.impl.javase.Executor$1$1.run(Executor.java:134)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1129)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:924)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
```

what is really weird is that, if I run the same project from inside netbeans, everything went fine....
So I don't really know what is going on with eclipse

I tried to debug the parser and here is the output for the `Mo-Fr 10:00-24:00;` input string:

```
Call:   rules
  Call:   rule
    Call:   comment(LOOKING AHEAD...)
<DEFAULT>Current character : M (77) at line 1 column 1
   No string literal matches possible.
   Starting NFA to match one of : { <HYPHEN>, <MINUTES>, <WS>, <MONTH>, 
     <MODIFIER>, <AM>, <PM>, <NUMBER>, <WEEKDAY>, 
     <HOLIDAYS>, <WEEKDAY3> }
<DEFAULT>Current character : M (77) at line 1 column 1
   Possible kinds of longer matches : { <WEEKDAY>, <WEEKDAY3>, <WEEKDAYDE>, <MONTH>, 
     <HOLIDAYS>, <EVENTS> }
<DEFAULT>Current character : o (111) at line 1 column 2
   Currently matched the first 2 characters as a <WEEKDAY> token.
   Possible kinds of longer matches : { <WEEKDAY3> }
<DEFAULT>Current character : - (45) at line 1 column 3
   Currently matched the first 2 characters as a <WEEKDAY> token.
   Putting back 1 characters into the input stream.
****** FOUND A <WEEKDAY> MATCH (Mo) ******

      Visited token: <<WEEKDAY>: "[c@6f80f69" at line 1 column 1>; Expected token: <"\"">
    Return: comment(LOOKAHEAD FAILED)
    Call:   year_selector(LOOKING AHEAD...)
<DEFAULT>Current character : - (45) at line 1 column 3
   No string literal matches possible.
   Starting NFA to match one of : { <HYPHEN>, <MINUTES>, <WS>, <MONTH>, 
     <MODIFIER>, <AM>, <PM>, <NUMBER>, <WEEKDAY>, 
     <HOLIDAYS>, <WEEKDAY3> }
<DEFAULT>Current character : - (45) at line 1 column 3
   Currently matched the first 1 characters as a <HYPHEN> token.
****** FOUND A <HYPHEN> MATCH (-) ******

      Call:   year_range(LOOKING AHEAD...)
        Call:   year(LOOKING AHEAD...)
        Return: year(LOOKAHEAD FAILED)
      Return: year_range(LOOKAHEAD FAILED)
    Return: year_selector(LOOKAHEAD FAILED)
    Call:   week_selector(LOOKING AHEAD...)
      Visited token: <<WEEKDAY>: "[c@6f80f69" at line 1 column 1>; Expected token: <"week">
    Return: week_selector(LOOKAHEAD FAILED)
    Call:   date_selector(LOOKING AHEAD...)
    Return: date_selector(LOOKAHEAD FAILED)
    Visited token: <<WEEKDAY>: "[c@6f80f69" at line 1 column 1>; Expected token: <":">
    Visited token: <<WEEKDAY>: "[c@6f80f69" at line 1 column 1>; Expected token: <"24/7">
    Call:   weekday_selector(LOOKING AHEAD...)
      Call:   weekday_range(LOOKING AHEAD...)
        Call:   weekday(LOOKING AHEAD...)
          Visited token: <<WEEKDAY>: "[c@6f80f69" at line 1 column 1>; Expected token: <<WEEKDAY>>
        Return: weekday(LOOKAHEAD SUCCEEDED)
        Visited token: <<HYPHEN>: "-" at line 1 column 3>; Expected token: <<HYPHEN>>
        Call:   weekday(LOOKING AHEAD...)
<DEFAULT>Current character : F (70) at line 1 column 4
   No string literal matches possible.
   Starting NFA to match one of : { <HYPHEN>, <MINUTES>, <WS>, <MONTH>, 
     <MODIFIER>, <AM>, <PM>, <NUMBER>, <WEEKDAY>, 
     <HOLIDAYS>, <WEEKDAY3> }
<DEFAULT>Current character : F (70) at line 1 column 4
   Possible kinds of longer matches : { <WEEKDAY>, <WEEKDAY3>, <WEEKDAYDE>, <MONTH> }
<DEFAULT>Current character : r (114) at line 1 column 5
   Currently matched the first 2 characters as a <WEEKDAY> token.
   Possible kinds of longer matches : { <WEEKDAY3> }
<DEFAULT>Current character :   (32) at line 1 column 6
   Currently matched the first 2 characters as a <WEEKDAY> token.
   Putting back 1 characters into the input stream.
****** FOUND A <WEEKDAY> MATCH (Fr) ******

          Visited token: <<WEEKDAY>: "[c@68bd1b55" at line 1 column 4>; Expected token: <<WEEKDAY>>
        Return: weekday(LOOKAHEAD SUCCEEDED)
      Return: weekday_range(LOOKAHEAD SUCCEEDED)
<DEFAULT>Current character :   (32) at line 1 column 6
   Currently matched the first 1 characters as a " " token.
   Possible string literal matches : { " to " } 
<DEFAULT>Current character : 1 (49) at line 1 column 7
   No string literal matches possible.
   No more string literal token matches are possible.
   Starting NFA to match one of : {  }
<DEFAULT>Current character : 1 (49) at line 1 column 7
   Currently matched the first 1 characters as a " " token.
   Putting back 1 characters into the input stream.
****** FOUND A " " MATCH ( ) ******

<DEFAULT>Current character : 1 (49) at line 1 column 7
   No string literal matches possible.
   Starting NFA to match one of : { <HYPHEN>, <MINUTES>, <WS>, <MONTH>, 
     <MODIFIER>, <AM>, <PM>, <NUMBER>, <WEEKDAY>, 
     <HOLIDAYS>, <WEEKDAY3> }
<DEFAULT>Current character : 1 (49) at line 1 column 7
   Currently matched the first 1 characters as a <NUMBER> token.
   Possible kinds of longer matches : { <HYPHEN>, <MINUTES>, <WS>, <MONTH>, 
     <MODIFIER>, <AM>, <PM>, <NUMBER>, <WEEKDAY>, 
     <HOLIDAYS>, <WEEKDAY3> }
<DEFAULT>Current character : 0 (48) at line 1 column 8
   Currently matched the first 2 characters as a <NUMBER> token.
   Possible kinds of longer matches : { <HYPHEN>, <MINUTES>, <WS>, <MONTH>, 
     <MODIFIER>, <AM>, <PM>, <NUMBER>, <WEEKDAY>, 
     <HOLIDAYS>, <WEEKDAY3> }
<DEFAULT>Current character : : (58) at line 1 column 9
   Currently matched the first 2 characters as a <NUMBER> token.
   Putting back 1 characters into the input stream.
****** FOUND A <NUMBER> MATCH (10) ******

      Visited token: <<NUMBER>: "10" at line 1 column 7>; Expected token: <",">
    Return: weekday_selector(LOOKAHEAD SUCCEEDED)
    Visited token: <<NUMBER>: "10" at line 1 column 7>; Expected token: <",">
    Call:   holiday_sequence(LOOKING AHEAD...)
      Call:   holiday(LOOKING AHEAD...)
        Visited token: <<WEEKDAY>: "[c@6f80f69" at line 1 column 1>; Expected token: <<HOLIDAYS>>
      Return: holiday(LOOKAHEAD FAILED)
    Return: holiday_sequence(LOOKAHEAD FAILED)
    Visited token: <<WEEKDAY>: "[c@6f80f69" at line 1 column 1>; Expected token: <",">
    Call:   weekday_selector(LOOKING AHEAD...)
      Call:   weekday_range(LOOKING AHEAD...)
        Call:   weekday(LOOKING AHEAD...)
          Visited token: <<WEEKDAY>: "[c@6f80f69" at line 1 column 1>; Expected token: <<WEEKDAY>>
        Return: weekday(LOOKAHEAD SUCCEEDED)
        Visited token: <<HYPHEN>: "-" at line 1 column 3>; Expected token: <<HYPHEN>>
        Call:   weekday(LOOKING AHEAD...)
          Visited token: <<WEEKDAY>: "[c@68bd1b55" at line 1 column 4>; Expected token: <<WEEKDAY>>
        Return: weekday(LOOKAHEAD SUCCEEDED)
      Return: weekday_range(LOOKAHEAD SUCCEEDED)
      Visited token: <<NUMBER>: "10" at line 1 column 7>; Expected token: <",">
    Return: weekday_selector(LOOKAHEAD SUCCEEDED)
    Visited token: <<WEEKDAY>: "[c@6f80f69" at line 1 column 1>; Expected token: <",">
    Call:   weekday_selector(LOOKING AHEAD...)
      Call:   weekday_range(LOOKING AHEAD...)
        Call:   weekday(LOOKING AHEAD...)
          Visited token: <<WEEKDAY>: "[c@6f80f69" at line 1 column 1>; Expected token: <<WEEKDAY>>
        Return: weekday(LOOKAHEAD SUCCEEDED)
        Visited token: <<HYPHEN>: "-" at line 1 column 3>; Expected token: <<HYPHEN>>
        Call:   weekday(LOOKING AHEAD...)
          Visited token: <<WEEKDAY>: "[c@68bd1b55" at line 1 column 4>; Expected token: <<WEEKDAY>>
        Return: weekday(LOOKAHEAD SUCCEEDED)
      Return: weekday_range(LOOKAHEAD SUCCEEDED)
      Visited token: <<NUMBER>: "10" at line 1 column 7>; Expected token: <",">
    Return: weekday_selector(LOOKAHEAD SUCCEEDED)
    Call:   weekday_selector
      Call:   weekday_range
        Call:   weekday
          Visited token: <<WEEKDAY>: "[c@6f80f69" at line 1 column 1>; Expected token: <<WEEKDAY>>
          Consumed token: <<WEEKDAY>: "[c@6f80f69" at line 1 column 1>
        Return: weekday
        Visited token: <<HYPHEN>: "-" at line 1 column 3>; Expected token: <<HYPHEN>>
        Call:   weekday(LOOKING AHEAD...)
          Visited token: <<WEEKDAY>: "[c@68bd1b55" at line 1 column 4>; Expected token: <<WEEKDAY>>
        Return: weekday(LOOKAHEAD SUCCEEDED)
        Visited token: <<HYPHEN>: "-" at line 1 column 3>; Expected token: <<HYPHEN>>
        Call:   weekday(LOOKING AHEAD...)
          Visited token: <<WEEKDAY>: "[c@68bd1b55" at line 1 column 4>; Expected token: <<WEEKDAY>>
        Return: weekday(LOOKAHEAD SUCCEEDED)
        Visited token: <<HYPHEN>: "-" at line 1 column 3>; Expected token: <<HYPHEN>>
        Consumed token: <<HYPHEN>: "-" at line 1 column 3>
        Call:   weekday
          Visited token: <<WEEKDAY>: "[c@68bd1b55" at line 1 column 4>; Expected token: <<WEEKDAY>>
          Consumed token: <<WEEKDAY>: "[c@68bd1b55" at line 1 column 4>
        Return: weekday
      Return: weekday_range
    Return: weekday_selector
  Return: rule
Return: rules
```

You can see that after the `****** FOUND A <WEEKDAY> MATCH (Mo) ******` debug line, the `Mo` weekday token is converted into what seems to be an object reference (`[c@6f80f69`) in the token.image of the next debugged function (the `jj_scan_token` function that prints the `Visited token: <<WEEKDAY>: "[c@6f80f69" at line 1 column 1>; Expected token: <"\"">
` line).
The problem seems to occur into the `getNextToken()` function of the generated `OpeningHoursParserTokenManager` class but I really don't understand what might cause this and why the exact same code is working into netbeans and not into eclipse (I copy pasted the files from eclipse to netbeans and didn't regenerate them with javaCC so they are exactly the same). 
Do you have any idea of what might cause this issue (this is kind of turning me crazy so I would really appreciate any sugestion ;) )

**Comment by ramsestom** [comment]
Ok found the source of the issue. Was due to codenameone not handeling StringBuilder.append(char[]) (that default into StringBuilder.append(Object), hence the issue...). Still don't know why it was working into netbeans and not into eclipse but at least I could fix the issue ;)
