### ISSUE TITLE
Crash for opening_hours=8095652114 or opening_hours=3287182465

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/OpeningHoursParser#26]
I checked all opening_hours values in OSM (to test my own code) and I noticed that `opening_hours=8095652114` triggers crash in this parser.

```
Exception in thread "main" java.lang.NumberFormatException: For input string: "8095652114"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at ch.poole.openinghoursparser.OpeningHoursParser.jj_3R_25(OpeningHoursParser.java:2810)
	at ch.poole.openinghoursparser.OpeningHoursParser.jj_3R_33(OpeningHoursParser.java:1957)
	at ch.poole.openinghoursparser.OpeningHoursParser.jj_3R_35(OpeningHoursParser.java:3113)
	at ch.poole.openinghoursparser.OpeningHoursParser.jj_3_85(OpeningHoursParser.java:2890)
	at ch.poole.openinghoursparser.OpeningHoursParser.jj_2_85(OpeningHoursParser.java:1807)
	at ch.poole.openinghoursparser.OpeningHoursParser.rule(OpeningHoursParser.java:980)
	at ch.poole.openinghoursparser.OpeningHoursParser.rules(OpeningHoursParser.java:1092)
	at starter.main(starter.java:155)
```

it is called as follows

```
value = "8095652114";
ByteArrayInputStream input = new ByteArrayInputStream(value.getBytes(StandardCharsets.UTF_8));
OpeningHoursParser parser = new OpeningHoursParser(input);
ArrayList<Rule> rules = parser.rules(true);
```

**Comment by simonpoole** [comment]
> 
> 
> I checked all opening_hours values in OSM (to test my own code) and I noticed that `opening_hours=8095652114` triggers crash in this parser.

Ahh, the test data already covers all unique OH strings (at least at the time I generated it) including the strings in question. It was actually expected that NFEs could occur (see the test code) but not documented. I've changed the code in 0.17.1 so that a ParseException is thrown as for most other issues, which is more user friendly in any case.

**Comment by simonpoole** [comment]
Changed in https://github.com/simonpoole/OpeningHoursParser/commit/1f7e0499ad5002a6c003c2f19f0aa30955734264

**Comment by matkoniecz** [comment]
Thanks!
