### ISSUE TITLE
Time ranges between days not handeled 

### ISSUE THREAD

**Issue by eddywatta** [simonpoole/OpeningHoursParser#39]
I noticed that the parser gives a ParseException when processing times range between days, for example while processing the following range: "Mo-Fr 18:00-02:00".
Shouldn't this case be covered? It's common for bars/pubs/disco to open before midnight and close after. 

This is the exception returned while processing previous range:
```
ch.poole.openinghoursparser.ParseException: End time earlier than start time at line 1, column 17
	at ch.poole.openinghoursparser.OpeningHoursParser.timespan(OpeningHoursParser.java:294)
	at ch.poole.openinghoursparser.OpeningHoursParser.time_selector(OpeningHoursParser.java:337)
	at ch.poole.openinghoursparser.OpeningHoursParser.rule(OpeningHoursParser.java:1069)
	at ch.poole.openinghoursparser.OpeningHoursParser.rules(OpeningHoursParser.java:1094)
	...
```

**Comment by simonpoole** [comment]
You need to turn strict mode off.
